<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>netstandard2.0</TargetFramework>
        <LangVersion>14</LangVersion>
        <RootNamespace>DataFixerUpper</RootNamespace>
        <IsAotCompatible Condition="$([MSBuild]::IsTargetFrameworkCompatible('$(TargetFramework)', 'net8.0'))">true</IsAotCompatible>
        <IsTrimmable Condition="$([MSBuild]::IsTargetFrameworkCompatible('$(TargetFramework)', 'net6.0'))">true</IsTrimmable>
        <Nullable>disable</Nullable>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <DocumentationFile>XmlDocs.xml</DocumentationFile>
        <Version>2.0.0-alpha</Version>
        <PackageReleaseNotes>Forward to netstandard2.0, align apis to original DFU</PackageReleaseNotes>
    </PropertyGroup>

    <PropertyGroup>
        <Copyright>MIT</Copyright>
        <IsPackable>true</IsPackable>
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
        <Title>Porting of com.mojang.datafixerupper</Title>
        <Description>C# porting of com.mojang.datafixerupper.</Description>
        <PackageTags>datafixerupper, mojang</PackageTags>
        <PackageProjectUrl>https://github.com/Chrise2024/DataFixerUpper</PackageProjectUrl>
        <RepositoryUrl>https://github.com/Chrise2024/DataFixerUpper</RepositoryUrl>
        <RepositoryType>Github</RepositoryType>
        <PackageLicenseFile>LICENSE</PackageLicenseFile>
        <PackageReadmeFile>README.md</PackageReadmeFile>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="System.Text.Json" Version="10.0.12"/>
        <PackageReference Include="System.Collections.Immutable" Version="10.0.12"/>
    </ItemGroup>

    <ItemGroup>
        <None Include="XmlDocs.xml"/>
        <None Include="../Licenses/*.txt">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
        <None Include="../README.md" Pack="true" PackagePath="">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
        <None Include="../LICENSE" Pack="true" PackagePath="">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
    </ItemGroup>
</Project>
