<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <LangVersion>14</LangVersion>
        <RootNamespace>DataFixerUpper</RootNamespace>
        <IsAotCompatible>true</IsAotCompatible>
        <IsTrimmable>true</IsTrimmable>
        <Nullable>enable</Nullable>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <DocumentationFile>XmlDocs.xml</DocumentationFile>
    </PropertyGroup>
    
    <PropertyGroup>
        <Copyright>MIT</Copyright>
        <IsPackable>true</IsPackable>
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
        <Title>Porting of com.mojang.datafixerupper</Title>
        <Description>C# porting of com.mojang.datafixerupper.</Description>
        <PackageTags>datafixerupper, mojang</PackageTags>
        <PackageProjectUrl>https://github.com/Chrise2024/DataFixerUpper</PackageProjectUrl>
        <RepositoryUrl>https://github.com/Chrise2024/DataFixerUpper</RepositoryUrl>
        <RepositoryType>Github</RepositoryType>
        <PackageLicenseFile>LICENSE</PackageLicenseFile>
        <PackageReadmeFile>README.md</PackageReadmeFile>
    </PropertyGroup>

    <ItemGroup>
        <None Include="XmlDocs.xml"/>
        <None Include="../Licenses/*.txt" >
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
        <None Include="../README.md" Pack="true" PackagePath="">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
        <None Include="../LICENSE" Pack="true" PackagePath="">
          <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
    </ItemGroup>
</Project>
